baseURL: https://rotex1800.de
languageCode: de-de
title: Rotex 1800 e.V.
theme: hugo-whisper-theme
build:
  writeStats: true

params:
  addFrame: true
  logo:
    standard: /img/logo.png

taxonomies:
  category: categories

enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true

summaryLength: 15

menus:
  legal:
    - name: Satzung
      url: /satzung
      weight: 1
    - name: Impressum
      url: /impressum
      weight: 2
  main:
    - name: Posts
      url: /posts
      weight: 1
    - name: Über uns
      url: /über-uns
      weight: 3
    - name: Kalender
      url: /kalender
      weight: 4
    - name: Downloads
      url: /downloads
      weight: 5